spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_ID}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
server:
  port: ${PROD_SERVER_PORT}
  ssl:
    key-store: ${KET_STORE_PATH}
    key-store-type: PKCS12
    key-store-password: 1234
