spring:
  profiles:
    active: test
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  data:
    web:
      pageable:
        default-page-size: 20

server:
  port: 8080

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

ncp:
  end_point: ${ENDPOINT}
  region_name: ${REGION_NAME}
  access_key: ${ACCESS_KEY}
  secret_key: ${SECRET_KEY}
  bucket_name: ${BUCKET_NAME}
  image_folder_name: ${IMAGE_FOLDER_NAME}