spring:
  profiles:
    active: test
    include:
      - security
      - storage
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  data:
    web:
      pageable:
        default-page-size: 20

server:
  port: 8080

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINES}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600