cloud:
  aws:
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
    s3:
      bucket: ${BUCKET_NAME}
      bucket_path: ${BUCKET_PATH}
    region:
      static: ap-northeast-2
    stack:
      auto: false
