version: "3.7"

services:
  db:
    image: mysql:8.0.22
    platform: linux/amd64
    ports:
      - "3308:3306"
    container_name: pinata-db-containner
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
#    env_file: ../.env
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_pinata
    command: # 명령어 실행
      - --lower_case_table_names=1 # 대소문자 구분
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
